name: fetch
description: "Fetches oocana CLI, ovmlayer tools, and rootfs - core download logic without installation assumptions"
inputs:
  token:
    description: "GitHub token"
    required: true
    default: ${{ github.token }}
  architecture:
    description: "architecture, either amd64 or arm64"
    required: true
  destination:
    description: "Destination directory for downloaded files"
    required: true
  oocana:
    description: "oocana tag (supports 'latest' or specific version like v0.30.2)"
    required: false
    default: latest
  ovmlayer:
    description: "ovmlayer version"
    required: false
    default: latest
  rootfs:
    description: "rootfs tar"
    required: false
    default: "server-base@0.5.0"
  platform:
    description: "Platform: studio or cloud"
    required: false
    default: "studio"
  ovmlayer_app_id:
    description: "GitHub App ID for downloading ovmlayer from private repo"
    required: true
  ovmlayer_app_private_key:
    description: "GitHub App Private Key for downloading ovmlayer"
    required: true

outputs:
  oocana_version:
    description: "Resolved oocana version"
    value: ${{ steps.oocana-version.outputs.version }}
  ovmlayer_version:
    description: "Resolved ovmlayer version"
    value: ${{ steps.ovmlayer-version.outputs.version }}
  rootfs_version:
    description: "Rootfs version used"
    value: ${{ inputs.rootfs }}

runs:
  using: "composite"
  steps:
    - name: Validate architecture
      run: |
        if [ "${{ inputs.architecture }}" != "amd64" ] && [ "${{ inputs.architecture }}" != "arm64" ]; then
          echo "Invalid architecture: ${{ inputs.architecture }}"
          exit 1
        fi
      shell: bash

    - name: Generate GitHub App token for ovmlayer
      id: ovmlayer-token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ inputs.ovmlayer_app_id }}
        private-key: ${{ inputs.ovmlayer_app_private_key }}
        owner: oomol
        repositories: ovmlayer,ovmlayer-next

    - name: Resolve oocana version
      id: oocana-version
      run: |
        if [ "${{ inputs.oocana }}" = "latest" ]; then
          echo "version=$(gh release list --repo oomol/oocana-rust | head -n 1 | awk '{print $1}')" >> $GITHUB_OUTPUT
        else
          echo "version=${{ inputs.oocana }}" >> $GITHUB_OUTPUT
        fi
      env:
        GH_TOKEN: ${{ inputs.token }}
      shell: bash

    - name: Set architecture-specific variables
      id: arch-vars
      run: |
        if [ "${{ inputs.architecture }}" = "amd64" ]; then
          echo "oocana_binary=oocana-cli-x86_64-unknown-linux-gnu" >> $GITHUB_OUTPUT
          echo "ovmlayer_pattern=*amd64*" >> $GITHUB_OUTPUT
        else
          echo "oocana_binary=oocana-cli-aarch64-unknown-linux-gnu" >> $GITHUB_OUTPUT
          echo "ovmlayer_pattern=*arm64*" >> $GITHUB_OUTPUT
        fi

        if [ "${{ inputs.platform }}" = "cloud" ]; then
          echo "ovmlayer_repo=oomol/ovmlayer-next" >> $GITHUB_OUTPUT
        else
          echo "ovmlayer_repo=oomol/ovmlayer" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Resolve ovmlayer version
      id: ovmlayer-version
      run: |
        if [ "${{ inputs.ovmlayer }}" = "latest" ]; then
          version=$(gh release list --repo ${{ steps.arch-vars.outputs.ovmlayer_repo }} --limit 1 | awk '{print $1}')
          echo "version=$version" >> $GITHUB_OUTPUT
        else
          echo "version=${{ inputs.ovmlayer }}" >> $GITHUB_OUTPUT
        fi
      env:
        GH_TOKEN: ${{ steps.ovmlayer-token.outputs.token }}
      shell: bash

    - name: Create destination directory
      run: mkdir -p "${{ inputs.destination }}"
      shell: bash

    - name: Download oocana CLI
      run: |
        gh release download ${{ steps.oocana-version.outputs.version }} \
          --repo oomol/oocana-rust \
          --pattern "${{ steps.arch-vars.outputs.oocana_binary }}.tar.gz" \
          --clobber \
          -O ${{ runner.temp }}/oocana-cli.tar.gz
        tar -xf ${{ runner.temp }}/oocana-cli.tar.gz -C ${{ runner.temp }}
        mv ${{ runner.temp }}/${{ steps.arch-vars.outputs.oocana_binary }} ${{ inputs.destination }}/oocana
        chmod +x ${{ inputs.destination }}/oocana
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}

    - name: Download ovmlayer
      run: |
        gh release download ${{ steps.ovmlayer-version.outputs.version }} \
          --repo ${{ steps.arch-vars.outputs.ovmlayer_repo }} \
          --pattern "${{ steps.arch-vars.outputs.ovmlayer_pattern }}" \
          --clobber \
          -O ${{ runner.temp }}/ovmlayer.tar.zst
      shell: bash
      env:
        GH_TOKEN: ${{ steps.ovmlayer-token.outputs.token }}

    - name: Extract ovmlayer
      run: |
        rm -f ${{ runner.temp }}/ovmlayer.tar
        zstd -d ${{ runner.temp }}/ovmlayer.tar.zst -o ${{ runner.temp }}/ovmlayer.tar
        tar -xf ${{ runner.temp }}/ovmlayer.tar -C ${{ inputs.destination }}
      shell: bash

    - name: Download rootfs
      run: |
        gh release download ${{ inputs.rootfs }} \
          --repo oomol/ovmlayer-rootfs \
          --pattern "${{ inputs.architecture }}*" \
          -O ${{ inputs.destination }}/rootfs.tar
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}

    - name: Write versions.json
      run: |
        cat > ${{ inputs.destination }}/versions.json << EOF
        {
          "oocana": "${{ steps.oocana-version.outputs.version }}",
          "ovmlayer": "${{ steps.ovmlayer-version.outputs.version }}",
          "rootfs": "${{ inputs.rootfs }}"
        }
        EOF
      shell: bash

    - name: Show downloaded files
      run: |
        echo "Downloaded files to ${{ inputs.destination }}:"
        ls -lh ${{ inputs.destination }}
      shell: bash
