name: "setup ovmlayer"
description: "setup ovmlayer on ubuntu-latest"
inputs:
  token:
    description: "GitHub token"
    required: true
    default: ${{ github.token }}
  rootfs:
    description: "rootfs tar"
    required: false
    default: "https://github.com/oomol/ovmlayer-rootfs/releases/download/base-rootfs%400.2.1/arm64-rootfs.tar"

runs:
  using: "composite"
  steps:
    - name: download ovmlayer
      run: cd .. && npm install @oomol/ovmlayer@latest
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.token }}
    - name: move ovmlayer to PATH
      run: |
        mv ../node_modules/@oomol/ovmlayer ../ovmlayer
        cd ..
        ln -sf $(pwd)/ovmlayer/ovmlayer /usr/local/bin/ovmlayer
      shell: bash
    - name: setup ovmlayer environment
      run: |
        sudo apt update && sudo apt install -y --no-install-recommends locales-all tar xz-utils uuid-runtime
      shell: bash
    - name: download base rootfs
      run: |
        curl -L ${{inputs.rootfs}} -o base_rootfs.tar
      shell: bash
    - name: setup ovmlayer
      run: |
        ovmlayer setup dev --base-rootfs=$(pwd)/base_rootfs.tar --layer-disk=/tmp/layer-disk > /dev/null 2>&1
      shell: bash
