name: build-context
description: "Prepares oocana build context - downloads binaries to workspace for Docker multi-architecture builds"
inputs:
  token:
    description: "GitHub token"
    required: true
    default: ${{ github.token }}
  architecture:
    description: "architecture, either amd64 or arm64"
    required: false
    default: "amd64"
  oocana:
    description: "oocana tag"
    required: false
    default: v0.30.2
  ovmlayer:
    description: "ovmlayer version"
    required: false
    default: ovmlayer@0.5.1
  rootfs:
    description: "rootfs tar"
    required: false
    default: "server-base@0.5.0"

runs:
  using: "composite"
  steps:
    - name: Fetch binaries to workspace
      uses: ./.github/actions/fetch
      with:
        token: ${{ inputs.token }}
        architecture: ${{ inputs.architecture }}
        destination: ${{ github.workspace }}/${{ inputs.architecture }}
        oocana: ${{ inputs.oocana }}
        ovmlayer: ${{ inputs.ovmlayer }}
        rootfs: ${{ inputs.rootfs }}