name: build-context
description: "Prepares oocana build context - downloads binaries to workspace for Docker multi-architecture builds"
inputs:
  token:
    description: "GitHub token"
    required: true
    default: ${{ github.token }}
  architecture:
    description: "architecture, either amd64 or arm64"
    required: false
    default: "amd64"
  oocana:
    description: "oocana tag"
    required: false
    default: latest
  ovmlayer:
    description: "ovmlayer version"
    required: false
    default: latest
  rootfs:
    description: "rootfs tar"
    required: false
    default: "server-base@0.5.0"
  platform:
    description: "Platform: studio or cloud"
    required: false
    default: "studio"
  ovmlayer_app_id:
    description: "GitHub App ID for downloading ovmlayer from private repo"
    required: true
  ovmlayer_app_private_key:
    description: "GitHub App Private Key for downloading ovmlayer"
    required: true

outputs:
  oocana_version:
    description: "Resolved oocana version"
    value: ${{ steps.fetch.outputs.oocana_version }}
  ovmlayer_version:
    description: "Resolved ovmlayer version"
    value: ${{ steps.fetch.outputs.ovmlayer_version }}
  rootfs_version:
    description: "Rootfs version used"
    value: ${{ steps.fetch.outputs.rootfs_version }}

runs:
  using: "composite"
  steps:
    - name: Fetch binaries to workspace
      id: fetch
      uses: ./.github/actions/fetch
      with:
        token: ${{ inputs.token }}
        architecture: ${{ inputs.architecture }}
        destination: ${{ github.workspace }}/${{ inputs.architecture }}
        oocana: ${{ inputs.oocana }}
        ovmlayer: ${{ inputs.ovmlayer }}
        rootfs: ${{ inputs.rootfs }}
        platform: ${{ inputs.platform }}
        ovmlayer_app_id: ${{ inputs.ovmlayer_app_id }}
        ovmlayer_app_private_key: ${{ inputs.ovmlayer_app_private_key }}