name: build base image
on:
  pull_request:
    paths:
      - "base.dockerfile"
      - ".github/workflows/base.yaml"
  push:
    tags:
      - "base-rootfs*"
    paths:
      - "base.dockerfile"
      - ".github/workflows/base.yaml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  IMAGE_NAME: ghcr.io/oomol/base-rootfs

jobs:
  build-base:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{env.IMAGE_NAME}}
          flavor: |
            latest=auto
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          platforms: ${{ matrix.platform }}
          tags: ${{env.IMAGE_NAME}}:local
          labels: ${{ steps.meta.outputs.labels }}
          file: base.dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: get rootfs name
        id: rootfs
        run: |
          if [[ "${{ matrix.platform }}" == "linux/amd64" ]]; then
            echo "rootfs_name=amd64-rootfs" >> $GITHUB_OUTPUT
          else
            echo "rootfs_name=arm64-rootfs" >> $GITHUB_OUTPUT
          fi
      - name: export rootfs
        run: |
          docker run -d --name rootfs-export --platform ${{matrix.platform}} ${{env.IMAGE_NAME}}:local true
          docker export rootfs-export >> ${{steps.rootfs.outputs.rootfs_name}}.tar
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
      - name: Release
        uses: softprops/action-gh-release@v2
        if: ${{ github.event_name == 'push' &&  github.ref_type == 'tag' }}
        with:
          files: ${{steps.rootfs.outputs.rootfs_name}}.tar
          token: ${{ secrets.GITHUB_TOKEN }}
          append_body: true
          draft: false
          prerelease: false
          make_latest: true