name: build base rootfs
# Builds minimal Ubuntu-based rootfs with Zsh shell for ovmlayer layer testing.
# Creates multi-architecture (amd64/arm64) tar archives for basic Linux container foundation.

on:
  pull_request:
    paths:
      - ".github/workflows/build-base-rootfs.yaml"
      - "dockerfiles/base.dockerfile"
  push:
    tags:
      - "base-rootfs*"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-base:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker build
        run: |
          docker buildx build --load --platform ${{matrix.platform}} -t base-rootfs:local -f dockerfiles/base.dockerfile .
      - name: get rootfs name
        id: rootfs
        run: |
          if [[ "${{ matrix.platform }}" == "linux/amd64" ]]; then
            echo "rootfs_name=amd64-rootfs" >> $GITHUB_OUTPUT
          else
            echo "rootfs_name=arm64-rootfs" >> $GITHUB_OUTPUT
          fi
      - name: export rootfs
        run: |
          docker run -d --name rootfs-export base-rootfs:local true
          docker export rootfs-export >> ${{steps.rootfs.outputs.rootfs_name}}.tar
      - name: Release
        uses: softprops/action-gh-release@v2
        if: ${{ github.event_name == 'push' &&  github.ref_type == 'tag' }}
        with:
          files: ${{steps.rootfs.outputs.rootfs_name}}.tar
          token: ${{ secrets.GITHUB_TOKEN }}
          append_body: true
          draft: false
          prerelease: false
          make_latest: true