name: build base image
on:
  pull_request:
    paths:
      - "base.dockerfile"
      - ".github/workflows/base.yaml"
  push:
    paths:
      - "base.dockerfile"
      - ".github/workflows/base.yaml"
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/oomol/base-rootfs

jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{env.IMAGE_NAME}}
          tags: |
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}}
          flavor: |
            latest=auto
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.ref_type == 'tag' }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: base.dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max

  export-base:
    runs-on: ubuntu-latest
    needs: build-base
    if:  github.ref_type == 'tag'
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    steps:
      - name: get rootfs name
        id: rootfs
        run: |
          if [[ "${{ matrix.platform }}" == "linux/amd64" ]]; then
            echo "rootfs_name=amd64-rootfs" >> $GITHUB_OUTPUT
          else
            echo "rootfs_name=arm64-rootfs" >> $GITHUB_OUTPUT
          fi
      - name: export rootfs
        if : ${{ github.event_name == 'push' &&  github.ref_type == 'tag' }}
        run: |
          docker run -d --name base --platform ${{matrix.platform}} true
          docker export rootfs-export >> ${{steps.rootfs.outputs.rootfs_name}}.tar
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{steps.rootfs.outputs.rootfs_name}}.tar
          token: ${{ secrets.GITHUB_TOKEN }}
          append_body: true
          draft: false
          prerelease: false
          make_latest: true