name: "download ovmlayer environment"


on:
  pull_request:
    paths:
      - ".github/actions/ovmlayer/download.yml"
      - ".github/workflows/download.yaml"
      - "studio.dockerfile"
  workflow_dispatch:
    inputs:
      architecture:
        description: "Architecture to download for"
        type: choice
        options:
          - amd64
          - arm64
        default: amd64
      oocana:
        description: "Oocana version to download"
        required: false
        default: v0.30.2
      ovmlayer:
        description: "Ovmlayer version to download"
        required: false
        default: ovmlayer@0.5.1
      rootfs:
        description: "Rootfs tar to download"
        required: false
        default: base-rootfs@0.4.0

jobs:
  download-amd64:
    runs-on: ubuntu-latest
    if: ${{ inputs.architecture == 'amd64' || github.event_name == 'pull_request' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download ovmlayer and oocana
        uses: ./.github/actions/download
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          architecture: amd64
          oocana: v0.30.2
          ovmlayer: ovmlayer@0.5.1
          rootfs: base-rootfs@0.4.0
  download-arm64:
    runs-on: ubuntu-24.04-arm
    if: ${{ inputs.architecture == 'arm64' || github.event_name == 'pull_request' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download ovmlayer and oocana
        uses: ./.github/actions/download
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          architecture: arm64
          oocana: v0.30.2
          ovmlayer: ovmlayer@0.5.1
          rootfs: base-rootfs@0.4.0