name: test-package-layer
on:
  pull_request:
    paths:
      - .github/workflows/test-package-layer.yml
      - .github/actions/layer/**

jobs:
  test-layer-action:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/layer
        with:
          architecture: ${{ (runner.arch == 'ARM64' || runner.arch == 'ARM') && 'arm64' || 'amd64' }}