name: "test build-context action"
# this workflow is for test build-context action

on:
  pull_request:
    paths:
      - ".github/workflows/test-build-context.yml"
      - ".github/actions/build-context/*"
      - ".github/actions/fetch/*"
  workflow_dispatch:
    inputs:
      architecture:
        description: "Architecture to download for"
        type: choice
        options:
          - amd64
          - arm64
        default: amd64

jobs:
  test-amd64:
    runs-on: ubuntu-latest
    if: ${{ inputs.architecture == 'amd64' || github.event_name == 'pull_request' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare build context
        uses: ./.github/actions/build-context
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          architecture: amd64
  test-arm64:
    runs-on: ubuntu-24.04-arm
    if: ${{ inputs.architecture == 'arm64' || github.event_name == 'pull_request' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare build context
        uses: ./.github/actions/build-context
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          architecture: arm64